version: "3.9"
services:
    mariadb:
        build: requirements/mariadb
        image: mariadb
        container_name: MyMariadb
        init: true
        volumes:
            - mariadb_vol:${MYSQL_PATH}
        restart: on-failure
        env_file: .env
        networks:
            - inception

    wordpress:
        build: requirements/wordpress
        image: wordpress
        depends_on:
            - mariadb
        container_name: MyWordpress
        init: true
        volumes:
            - wordpress_vol:${WP_PATH}
        restart: always
        env_file: .env
        networks:
            - inception

    nginx:
        build: requirements/nginx
        image: nginx
        depends_on:
            - wordpress
        container_name: MyNginx
        init: true
        volumes:
            - wordpress_vol:${WP_PATH}
        deploy:
            restart_policy:
                condition: always
                delay: 3s
        ports:
            - 443:443	# HOST_PORT:CONTAINER_PORT, use HOST_PORT outside of docker network and CONTAINER_PORT inside
        env_file: .env	#can use specific env file for this container {.env is use by default}
        networks:
            - inception

networks:
    inception:
        driver: bridge

volumes:
    wordpress_vol:
        driver_opts:
            type: none
            device: /home/ggilbert/data/html
            o: bind
    mariadb_vol:
        driver_opts:
            type: none
            device: /home/ggilbert/data/mysql
            o: bind