version: "3.9"
services:
	nginx:
		build: requirements/nginx
		image: nginx
		container_name: nginx
		volume:
			- wordpress:${WP_PATH}
		restart: on-failure
		depends_on:
			- wordpress
		ports:
			- 443:443	# HOST_PORT:CONTAINER_PORT, use HOST_PORT outside of docker network and CONTAINER_PORT inside
		#use network to specifie your own network and don't use default one
		# env_file: .env	#can use specific env file for this container {.env is use by default}

	wordpress:
		build: requirements/wordpress
		image: wordpress
		container_name: wordpress
		volume:
			- wordpress:${WP_PATH}
		restart: on-failure
		depends_on:
			- mariadb
		# env_file: .env

	mariadb:
		build: requirements/mariadb
		image: mariadb
		container_name: mariadb
		volume:
			- mariadb:${MYSQL_PATH}
		restart: on-failure
		# env_file: .env

network:
	default:
		driver: bridge

volumes:
	wordpress:
		driver_opts:
			type: none
			device: /home/ggilbert/data/html
			o: bind
	mariadb:
		driver_opts:
			type: none
			device: /home/ggilbert/data/mysql
			o: bind