version: "3.9"
services:
  nginx:
    build: requirements/nginx
    ports:
      - 443:443
  wordpress:
    build: requirements/wordpress
    ports:
      - 443:9000
    volume:
      - .:/wordpress
  mariadb:
    build: requirements/mariaDB
    ports:
      - 443:3306
    volume:
      - .:/mariadb
